builders:
  error_handlers_generator:
    import: "package:error_handlers_generator/builder.dart"
    builder_factories: [ "errorHandlersBuilder" ]
    build_extensions: { ".dart": [ ".ehg.g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
